import Card from "./components/Card";
import Header from "./components/Header";
import SearchSidebar from "./components/SearchSidebar";

export const metadata = {
  title: "Search | Restaurant",
  description: "Generated by create next app",
};

export default function Search() {
  return (
    <>
      <Header />
      <div className="flex py-4 m-auto w-2/3 justify-between items-start">
        <SearchSidebar />
        <div className="w-5/6">
          <Card />
        </div>
      </div>
    </>
  );
}
