import RestaurantNav from "./components/RestaurantNav";
import Title from "./components/Title";
import Rating from "./components/Rating";
import Description from "./components/Description";
import Images from "./components/Images";
import ReservationCard from "./components/ReservationCard";
import axios from "axios";

export const metadata = {
  title: "Restaurant",
  description: "Generated by create next app",
};

async function resData(url: string) {
  const res = await axios.get(
    `http://localhost:3000/api/restaurant?url=${url}`
  );
  if (res.status === 200) {
    return res.data.data;
  }
}

export default async function RestaurantDetails({
  params,
}: {
  params: { slug: string };
}) {
  const data = await resData(params.slug);
  return (
    <>
      <div className="bg-white w-[70%] rounded p-3 shadow">
        <RestaurantNav />
        <Title title={data.name} />
        <Rating />
        <Description />
        <Images />
      </div>
      <div className="w-[27%] relative text-reg">
        <ReservationCard />
      </div>
    </>
  );
}
